### ISSUE TITLE
Closing bracket from selected function suggestion cannot be overwritten

### ISSUE THREAD

**Issue by juthilo** [php-integrator/atom-autocompletion#100] opened 2017-05-22 20:07 UTC
When I select a function from the autocomplete suggestions by pressing `Enter`, opening and closing brackets for that function are correctly inserted.

![screenshot 26](https://cloud.githubusercontent.com/assets/3535675/26326129/33b8c50a-3f3a-11e7-8aba-e95c752ca422.png)
![screenshot 27](https://cloud.githubusercontent.com/assets/3535675/26326136/37f3ed3e-3f3a-11e7-9f6e-683ea51564f8.png)

After filling in the arguments, I'm not able to "overwrite" the closing bracket. Typing `)` results in two closing brackets at the end of the function:

![screenshot 28](https://cloud.githubusercontent.com/assets/3535675/26326158/56b5bc20-3f3a-11e7-8bb6-b9e15ba60e20.png)

 Instead, I have to press the right arrow and then type the semicolon, which is cumbersome.

![screenshot 29](https://cloud.githubusercontent.com/assets/3535675/26326164/61e54840-3f3a-11e7-8048-6e6d6c400819.png)

**Comment by Gert-dev** [comment] 2017-05-24 18:29
I see. In theory I can handle this in the Atom package, but it will be hard to make it reusable for other software using the core without some kind of protocol extension there later on.

I'm wondering however if this is a problem I can/should solve specifically in my PHP autocompletion or if this is a broader problem across multiple languages in Atom. I can imagine there would be users that also would like this:

```
foo()
```

... to not insert an additional `()` when typing `(` when the cursor is just after foo. In the same line, I can imagine Go/Java/C/C++/D/... developers wanting the same thing. Maybe this would be more suited for a separate package or perhaps something configurable in the language-php package since it's not strictly related to autocompletion?

**Comment by juthilo** [comment] 2017-05-25 09:41
Yes, but _if_ the (theoretical) configuration is to insert soft closing brackets as it is right now, shouldn't this package honor that?

I'm not thoroughly familiar with the internals of Atom and how this package works, so maybe I'm misunderstanding something. However, right now, this "feels" like an incomplete feature implementation.

Also, I'm not sure if I was clear in my original post&mdash;the fact that autocomplete adds a closing bracket is perfectly fine, I would just like to be able to type over it when I need to add a semicolon at the end of the line.

**Comment by Gert-dev** [comment] 2017-05-27 12:59
You certainly do have a point. The main reason I pointed my finger towards Atom is because currently it also seems to do this in other places. What's strange is, I can't even seem to consistently reproduce this, in some cases where I have this:

```
foo('A|');
```

... typing an apostrophe will not add a new one, but instead replace the existing one (the cursor is at the vertical bar). But if I move the cursor back and try to do this again, it inserts a new pair of apostrophes.

This may have something to do with a somewhat picky check, for example, if you just start typing a string value inside a function call, `foo('test')`, in one go (i.e. without moving the cursor), Atom will be smart enough to overwrite the last apostrophe which it already inserted when you typed the opening apostrophe.

Whilst I was testing that, I noticed that Atom already seems to have the behavior you describe, as long as you type it all manually yourself, which might explain why that isn't working when you insert the text via an autocompletion suggestion from this package.

I'll have to investigate how and when Atom uses the overwrite behavior to see if I can insert suggestions in such a way that it will allow you to overwrite them.

**Comment by Gert-dev** [comment] 2018-02-01 19:22
This package is now deprecated as this functionality has been included in [the core](https://gitlab.com/php-integrator/core/) and [the base package](https://github.com/php-integrator/atom-base). I'm closing all issues with this generic message as the issue tracker is going to be disabled. Feel free to create new issues in either the core or the base package, if appropriate.

**Closed by Gert-dev** 2018-02-01 19:22 UTC
Labels: enhancement
